# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='archive file')),
                ('date', models.DateTimeField(verbose_name='archive file creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmcid', models.CharField(max_length=20, unique=True, verbose_name='Pubmed Central ID')),
                ('path', models.CharField(max_length=200, verbose_name='file path')),
                ('xml', models.TextField(blank=True, verbose_name='XML content')),
                ('text', models.TextField(blank=True, verbose_name='full text')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oac_search.Archive')),
            ],
        ),
    ]
