# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cleantext',
            field=models.TextField(blank=True, verbose_name='text without figures, tables, etc.'),
        ),
    ]
