# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oac_search', '0002_article_cleantext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pmcid',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Pubmed Central ID'),
        ),
    ]
